CREATE SCHEMA IF NOT EXISTS disney;

USE disney;

CREATE TABLE IF NOT EXISTS genres(
	ID INT AUTO_INCREMENT NOT NULL,
    GENRE_NAME VARCHAR(30) NOT NULL,
    URL_IMAGE VARCHAR(50),
    CONSTRAINT PK_genres_id PRIMARY KEY(id),
    CONSTRAINT UQ_genres_genre_name UNIQUE(GENRE_NAME)
);

CREATE TABLE IF NOT EXISTS characters(
	ID BIGINT AUTO_INCREMENT NOT NULL,
    AGE TINYINT UNSIGNED NOT NULL,
    WEIGHT DOUBLE NOT NULL,
    CHARACTER_NAME VARCHAR(50) NOT NULL,
    URL_IMAGE VARCHAR(50),
    CHARACTER_HISTORY VARCHAR(255),
    CONSTRAINT PK_characters_id PRIMARY KEY(ID),
    CONSTRAINT CK_characters_age CHECK(AGE <= 150),
    CONSTRAINT CK_characters_weight CHECK(WEIGHT <= 500.0)
);

CREATE TABLE IF NOT EXISTS movies_series(
	ID BIGINT AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    QUALIFICATION TINYINT UNSIGNED NOT NULL,
    URL_IMAGE VARCHAR(50),
    CONSTRAINT PK_movies_series_id PRIMARY KEY(ID),
    CONSTRAINT CK_movies_series_qualification CHECK(qualification <= 5)
);

CREATE TABLE IF NOT EXISTS movies_series_genres(
	ID BIGINT AUTO_INCREMENT NOT NULL,
    GENRE_ID INT NOT NULL,
    MOVIE_SERIE_ID BIGINT NOT NULL,
    CONSTRAINT PK_movies_series_genres_id PRIMARY KEY(ID),
    CONSTRAINT FK_movies_series_genres_genre_id FOREIGN KEY(GENRE_ID) REFERENCES disney.genres(ID),
    CONSTRAINT FK_movies_series_genres_movie_serie_id FOREIGN KEY(MOVIE_SERIE_ID) REFERENCES disney.movies_series(ID)
);