CREATE SCHEMA IF NOT EXISTS disney;

USE disney;

CREATE TABLE IF NOT EXISTS genres(
	ID INT AUTO_INCREMENT NOT NULL,
    GENRE_NAME VARCHAR(30) NOT NULL,
    URL_IMAGE VARCHAR(50),
    CONSTRAINT PK_genres_id PRIMARY KEY(id),
    CONSTRAINT UQ_genres_genre_name UNIQUE(GENRE_NAME)
);