CREATE SCHEMA IF NOT EXISTS disney;

USE disney;

CREATE TABLE IF NOT EXISTS genres(
	ID INT AUTO_INCREMENT NOT NULL,
    GENRE_NAME VARCHAR(30) NOT NULL,
    URL_IMAGE VARCHAR(50),
    CONSTRAINT PK_genres_id PRIMARY KEY(id),
    CONSTRAINT UQ_genres_genre_name UNIQUE(GENRE_NAME)
);

CREATE TABLE IF NOT EXISTS characters(
	ID BIGINT AUTO_INCREMENT NOT NULL,
    AGE TINYINT UNSIGNED NOT NULL,
    WEIGHT DOUBLE NOT NULL,
    CHARACTER_NAME VARCHAR(50) NOT NULL,
    URL_IMAGE VARCHAR(50),
    CHARACTER_HISTORY VARCHAR(255),
    CONSTRAINT PK_characters_id PRIMARY KEY(ID),
    CONSTRAINT CK_characters_age CHECK(AGE <= 150),
    CONSTRAINT CK_characters_weight CHECK(WEIGHT <= 500.0)
);